# 03. Sequence Extraction

Maps each transporter candidate gene ID to its protein sequence from the ITAG4.0 proteome, and writes a FASTA file for BLAST search against Arabidopsis.

**Input**: `dataset/processed/final_candidates.csv`, `dataset/reference/ITAG4.0_proteins.fasta`

**Output**: `dataset/processed/final_candidates_with_seq.csv`, `dataset/blast/tomato_candidates.fasta`

In [30]:
from Bio import SeqIO
from Bio import Blast

import scanpy as sc
import pandas as pd
import numpy as np

In [11]:
candidates = pd.read_csv("../dataset/processed/final_candidates.csv")
fasta_dict = SeqIO.to_dict(SeqIO.parse("../dataset/reference/ITAG4.0_proteins.fasta", "fasta"))
fasta_dict

{'Solyc00g500001.1.1': SeqRecord(seq=Seq('HGTVILLVYVDDIIITGFTAALIEDVTRAMHTTFKMKDLGSLHYFLGMEVSRIG...TMW'), id='Solyc00g500001.1.1', name='Solyc00g500001.1.1', description='Solyc00g500001.1.1', dbxrefs=[]),
 'Solyc00g500002.1.1': SeqRecord(seq=Seq('MPISPSRSTNSVDVPFHNPRLFHSLVGGLQYLTVTRPDIQFAVNYVAQKMHSLT...SEV'), id='Solyc00g500002.1.1', name='Solyc00g500002.1.1', description='Solyc00g500002.1.1', dbxrefs=[]),
 'Solyc00g500003.1.1': SeqRecord(seq=Seq('MTSPPWTARTVRRRRAWHDITAPWTARTVELRRAWHDITAFGQHTRSTDVGRGM...PW*'), id='Solyc00g500003.1.1', name='Solyc00g500003.1.1', description='Solyc00g500003.1.1', dbxrefs=[]),
 'Solyc00g500004.1.1': SeqRecord(seq=Seq('MACHARRSRLCALSKSGDAMPRPTLPSVCAVQGGDVMPRPMLPIAMMEWNARRS...RR*'), id='Solyc00g500004.1.1', name='Solyc00g500004.1.1', description='Solyc00g500004.1.1', dbxrefs=[]),
 'Solyc00g500005.1.1': SeqRecord(seq=Seq('MPSPPLDSTHDRMTSGVGCHHRPSTMHTEGQRRAWHDLTALGQHTRSDYIGHGM...IE*'), id='Solyc00g500005.1.1', name='Solyc00g500005.1.1', description='Solyc00g500005.1.1', dbxrefs=[]),
 'Solyc00g500006.1.1': SeqRecord(seq=Seq('MPDIVLPCVLSKVSDGMPRPTSSDRDDGMPRLTSFDRVCCPKAVMSCHARRSPTMRVVQ*'), id='Solyc00g500006.1.1', name='Solyc00g500006.1.1', description='Solyc00g500006.1.1', dbxrefs=[]),
 'Solyc00g500007.1.1': SeqRecord(seq=Seq('MPSYPLDGKHGRTTSGVTCYHRLWTAHTIERRRNTRSNDVERDMPTPPLNSTHG...IE*'), id='Solyc00g500007.1.1', name='Solyc00g500007.1.1', description='Solyc00g500007.1.1', dbxrefs=[]),
 'Solyc00g500008.1.1': SeqRecord(seq=Seq('MVRRHQAWHDITAFGQHTQSATRHRRYWTARMHTRSNDVRSVLPSSPLGSTHGR...AA*'), id='Solyc00g500008.1.1', name='Solyc00g500008.1.1', description='Solyc00g500008.1.1', dbxrefs=[]),
 'Solyc00g500009.1.1': SeqRecord(seq=Seq('MPSPPFDNTHGRTTTVHTVERRRAWHDITALGRHTRSNDVGSGMTSQPSDVTHG...VE*'), id='Solyc00g500009.1.1', name='Solyc00g500009.1.1', description='Solyc00g500009.1.1', dbxrefs=[]),
 'Solyc00g500010.1.1': SeqRecord(seq=Seq('MPSSPLGSTHGGMTSAWHAILAQGRQTLSNDVGRKMPSSPLGSTHDRTTSGAWH...TR*'), id='Solyc00g500010.1.1', name='Solyc00g500010.1.1', description='Solyc00g500010.1.1', dbxrefs=[]),
 'Solyc00g500011.1.1': SeqRecord(seq=Seq('MPRVVLPCVLSKGGGDVMPRPTSSDRACSPRVVMPCHIRSRLTVCTVQGRLFNA...EL*'), id='Solyc00g500011.1.1', name='Solyc00g500011.1.1', description='Solyc00g500011.1.1', dbxrefs=[]),
 'Solyc00g500012.1.1': SeqRecord(seq=Seq('MRRRRAWHANIAFEQHKQSDDIECVMQSPPLESTQGVACHHRPWTRNTVEQHRA...GRQ'), id='Solyc00g500012.1.1', name='Solyc00g500012.1.1', description='Solyc00g500012.1.1', dbxrefs=[]),
 'Solyc00g500013.1.1': SeqRecord(seq=Seq('MPRLTSFDRVCCPKVMFACHVGVVRPFVLPKEDDGMPRPTSSDYVYCPREVMAC...YP*'), id='Solyc00g500013.1.1', name='Solyc00g500013.1.1', description='Solyc00g500013.1.1', dbxrefs=[]),
 'Solyc00g500014.1.1': SeqRecord(seq=Seq('MPRPMSSDRAGSSRAMMSCHVTRSSIALMACHADVIQLCVLPKGDDGMPLLTSF...GR*'), id='Solyc00g500014.1.1', name='Solyc00g500014.1.1', description='Solyc00g500014.1.1', dbxrefs=[]),
 'Solyc00g500015.1.1': SeqRecord(seq=Seq('MTSLPFGSTHGRTTSGVACHHHLCTAHPVERRRAWHAILPLEAHTVERRRAWHD...SP*'), id='Solyc00g500015.1.1', name='Solyc00g500015.1.1', description='Solyc00g500015.1.1', dbxrefs=[]),
 'Solyc00g500016.1.1': SeqRecord(seq=Seq('MTSGVPCIISLGYRTRLDYVGRGMPSSLFESKHVKRSQAWHAVLPLETTQCQMT...TR*'), id='Solyc00g500016.1.1', name='Solyc00g500016.1.1', description='Solyc00g500016.1.1', dbxrefs=[]),
 'Solyc00g500017.1.1': SeqRecord(seq=Seq('MSLGHDTQSDDVGHGIPSKPLNSTHDRTTHTIGQYCPWHAIIALGQHTVLDKFG...TV*'), id='Solyc00g500017.1.1', name='Solyc00g500017.1.1', description='Solyc00g500017.1.1', dbxrefs=[]),
 'Solyc00g500018.1.1': SeqRecord(seq=Seq('MCAFQGLRGHAMRDIIQPVCCPRKIMECHNKFLPFVCAVQGPLKHATPDIARPC...YR*'), id='Solyc00g500018.1.1', name='Solyc00g500018.1.1', description='Solyc00g500018.1.1', dbxrefs=[]),
 'Solyc00g014290.1.1': SeqRecord(seq=Seq('MASHSGRRLTVFDVQGPCCHAPPDIVYLYLQSKGDDGMLCLRSTDRVSCRRSMM...HS*'), id='Solyc00g014290.1.1', name='Solyc00g014290.1.1', description='Solyc00g014290.1.1', dbxrefs=[]),
 'Solyc00g005280.1.1': SeqRecord(seq=Seq('MPCRTSFERVSHLKDINVMPRQKSSNHACCLKAMIACHVQLCVFSNGHGCMQRV...HA*'), id='Solyc00g005280.1.1', name='Solyc00g005280.1.1', description='Solyc00g005280.1.1', dbxrefs=[]),
 'Solyc00g500019.1.1': SeqRecord(seq=Seq('MEFQVDLVLSQDAPNLDLAYELMGIDQCSGYDRFDRKEGIVCIFRWGFPGKNRR...VF*'), id='Solyc00g500019.1.1', name='Solyc00g500019.1.1', description='Solyc00g500019.1.1', dbxrefs=[]),
 'Solyc00g500020.1.1': SeqRecord(seq=Seq('MAKKKAFTPLFYLASIVFLPWWISFSVNKWLESWVTNWWNTGQSQIVLNNIQEK...NF*'), id='Solyc00g500020.1.1', name='Solyc00g500020.1.1', description='Solyc00g500020.1.1', dbxrefs=[]),
 'Solyc00g500021.1.1': SeqRecord(seq=Seq('MSGSTGERSFADIITSIRYWVIHSITIPSLFIAGWLFVSTGLAYDVFGSPRPNE...QR*'), id='Solyc00g500021.1.1', name='Solyc00g500021.1.1', description='Solyc00g500021.1.1', dbxrefs=[]),
 'Solyc00g500022.1.1': SeqRecord(seq=Seq('MDKSKRPFLKFKRSFRRRLPPIQSGDRIDYRNMSLISRFISEQGKILSRRVNRL...NK*'), id='Solyc00g500022.1.1', name='Solyc00g500022.1.1', description='Solyc00g500022.1.1', dbxrefs=[]),
 'Solyc00g180440.1.1': SeqRecord(seq=Seq('MTRIKRGYIARRRRTKIRLFASSFRGAHSRLTRTITQQKIRALVSAHRDRDRKK...IHD'), id='Solyc00g180440.1.1', name='Solyc00g180440.1.1', description='Solyc00g180440.1.1', dbxrefs=[]),
 'Solyc00g500023.1.1': SeqRecord(seq=Seq('MLYLSMEDENKDLYLFVNSPGGWVIPGIAIYDTMQFVRPDIHTICLGLAASMGS...DL*'), id='Solyc00g500023.1.1', name='Solyc00g500023.1.1', description='Solyc00g500023.1.1', dbxrefs=[]),
 'Solyc00g500024.1.1': SeqRecord(seq=Seq('MGLPWYRVHTVVLNDPGRLLSVHIMHTALVAGWAGSMALYELAVFDPSDPVLDP...AA*'), id='Solyc00g500024.1.1', name='Solyc00g500024.1.1', description='Solyc00g500024.1.1', dbxrefs=[]),
 'Solyc00g500025.1.1': SeqRecord(seq=Seq('MRNTANKAIATPIKGVVPHPGATLPYSEFNGFNKSPTAVRLGPDLELFSTVCVA...IC*'), id='Solyc00g500025.1.1', name='Solyc00g500025.1.1', description='Solyc00g500025.1.1', dbxrefs=[]),
 'Solyc00g500026.1.1': SeqRecord(seq=Seq('MATQTVENSSRSGPRRTAVGDLLKPLNSEYGKVAPGWGTTPLMGVAMALFAGIS...LI*'), id='Solyc00g500026.1.1', name='Solyc00g500026.1.1', description='Solyc00g500026.1.1', dbxrefs=[]),
 'Solyc00g500027.1.1': SeqRecord(seq=Seq('AVRDESLIYGSQRGSSAYLNKVYDWFEERLEIQAIADDITSKYVPPHVNIFYCL...PL*'), id='Solyc00g500027.1.1', name='Solyc00g500027.1.1', description='Solyc00g500027.1.1', dbxrefs=[]),
 'Solyc00g500028.1.1': SeqRecord(seq=Seq('MSSSLGGWIYKNSPIPITKKPDLNDPVLRAKLAKGTIACNVGLAVLEPSMIGEP...LF*'), id='Solyc00g500028.1.1', name='Solyc00g500028.1.1', description='Solyc00g500028.1.1', dbxrefs=[]),
 'Solyc00g500029.1.1': SeqRecord(seq=Seq('MVREKVTVSTRTLQWKCVESRTDSKRLYYGRFILSPLMKGQADTIGIAMRRALL...IL*'), id='Solyc00g500029.1.1', name='Solyc00g500029.1.1', description='Solyc00g500029.1.1', dbxrefs=[]),
 'Solyc00g500030.1.1': SeqRecord(seq=Seq('MAKAIPKISSRRNGRISSRKGARRIPKGVIHVQASFNNTIVTVTDVRGRVVSWS...RV*'), id='Solyc00g500030.1.1', name='Solyc00g500030.1.1', description='Solyc00g500030.1.1', dbxrefs=[]),
 'Solyc00g500031.1.1': SeqRecord(seq=Seq('MIQPQTHLNVADNSGARELMCIRIIGASNRRYAHIGDVIVAVIKEAVPNMPLER...IW*'), id='Solyc00g500031.1.1', name='Solyc00g500031.1.1', description='Solyc00g500031.1.1', dbxrefs=[]),
 'Solyc00g500032.1.1': SeqRecord(seq=Seq('MKGISYRGNRISFGKYALQALEPAWITSRQIEAGRRAMTRNARRGGKIWVRIFP...IS*'), id='Solyc00g500032.1.1', name='Solyc00g500032.1.1', description='Solyc00g500032.1.1', dbxrefs=[]),
 'Solyc00g500033.1.1': SeqRecord(seq=Seq('MELRIKLVDLFIGKLRPRARGFNFFTVHKDNPKGLWVFFYQLGLSLHHPHGDGL...WM*'), id='Solyc00g500033.1.1', name='Solyc00g500033.1.1', description='Solyc00g500033.1.1', dbxrefs=[]),
 'Solyc00g500034.1.1': SeqRecord(seq=Seq('MLKKKKTEVYALGEHISMSADKARRVIDQIRGRSYEETLMILELMPYRACYPIL...EE*'), id='Solyc00g500034.1.1', name='Solyc00g500034.1.1', description='Solyc00g500034.1.1', dbxrefs=[]),
 'Solyc00g500035.1.1': SeqRecord(seq=Seq('MPLGTAIHNIEITLGKGGQLARAAGAVAKLIAKEGKSATLKLPSGEVRLISKNC...SK*'), id='Solyc00g500035.1.1', name='Solyc00g500035.1.1', description='Solyc00g500035.1.1', dbxrefs=[]),
 'Solyc00g500036.1.1': SeqRecord(seq=Seq('MAIHLYKTSTPSTRNGTVDSQVKSNPRNNLIYGQRRCGKGRNARGIITARHRGG...AV*'), id='Solyc00g500036.1.1', name='Solyc00g500036.1.1', description='Solyc00g500036.1.1', dbxrefs=[]),
 'Solyc00g500037.1.1': SeqRecord(seq=Seq('MRGHQFKSWIFELREILREIKNSHHFLDSWTQFNSVGSFIHIFFHQERFLKLFD...FM*'), id='Solyc00g500037.1.1', name='Solyc00g500037.1.1', description='Solyc00g500037.1.1', dbxrefs=[]),
 'Solyc00g500038.1.1': SeqRecord(seq=Seq('MYGWYELPKQEFLNSKQPVQIFTTKKYWILFRIGPERRRKAGMPIGIETTLVRS...NK*'), id='Solyc00g500038.1.1', name='Solyc00g500038.1.1', description='Solyc00g500038.1.1', dbxrefs=[]),
 'Solyc00g500039.1.1': SeqRecord(seq=Seq('MLIPQIPSLLLLREKKFTTRGPSTSTRHCSVRLSPIAENSPLLPPESGPCLSPS...TH*'), id='Solyc00g500039.1.1', name='Solyc00g500039.1.1', description='Solyc00g500039.1.1', dbxrefs=[]),
 'Solyc00g500040.1.1': SeqRecord(seq=Seq('MHEDNQFGRCGRTLLWISDHILHRALLSLPSPSSGYGRRNREEGRIPSPILTKK...KV*'), id='Solyc00g500040.1.1', name='Solyc00g500040.1.1', description='Solyc00g500040.1.1', dbxrefs=[]),
 'Solyc00g500041.1.1': SeqRecord(seq=Seq('MIIDTTEIETINSFSKLESLKEVYGIIWMLVPIVTLVLGITIGVLVIVWLEREI...SL*'), id='Solyc00g500041.1.1', name='Solyc00g500041.1.1', description='Solyc00g500041.1.1', dbxrefs=[]),
 'Solyc00g500042.1.1': SeqRecord(seq=Seq('KKQKQKDDFCFLTVWGMEAELPFGSPRKRPSFFEPIFKELEKKIGKFKKKYFLT...IN*'), id='Solyc00g500042.1.1', name='Solyc00g500042.1.1', description='Solyc00g500042.1.1', dbxrefs=[]),
 'Solyc00g500043.1.1': SeqRecord(seq=Seq('MIFQSFLLGNLVSLCMKIINSVVVVGLYYGFLTTFSIGPSYLFLLRALVMEEGT...IN*'), id='Solyc00g500043.1.1', name='Solyc00g500043.1.1', description='Solyc00g500043.1.1', dbxrefs=[]),
 'Solyc00g500044.1.1': SeqRecord(seq=Seq('MLIPQIPSLLLLREKKFTTRGPSTSTRHCSVRLSPIAENSPLLPPESGPCLSPS...TH*'), id='Solyc00g500044.1.1', name='Solyc00g500044.1.1', description='Solyc00g500044.1.1', dbxrefs=[]),
 'Solyc00g500045.1.1': SeqRecord(seq=Seq('MYGWYELPKQEFLNSKQPVQIFTTKKYWILFRIGPERRRKAGMPIGIETTLVRS...NK*'), id='Solyc00g500045.1.1', name='Solyc00g500045.1.1', description='Solyc00g500045.1.1', dbxrefs=[]),
 'Solyc00g500046.1.1': SeqRecord(seq=Seq('MRGHQFKSWIFELREILREIKNSHHFLDSWTQFNSVGSFIHIFFHQERFLKLFD...FM*'), id='Solyc00g500046.1.1', name='Solyc00g500046.1.1', description='Solyc00g500046.1.1', dbxrefs=[]),
 'Solyc00g500047.1.1': SeqRecord(seq=Seq('MAIHLYKTSTPSTRNGTVDSQVKSNPRNNLIYGQRRCGKGRNARGIITARHRGG...SK*'), id='Solyc00g500047.1.1', name='Solyc00g500047.1.1', description='Solyc00g500047.1.1', dbxrefs=[]),
 'Solyc00g277510.1.1': SeqRecord(seq=Seq('MTAILERRESESLWGRFCNWITSTENRLYIGWFGVLMIPTLLTATSVFIIAFIA...EPV'), id='Solyc00g277510.1.1', name='Solyc00g277510.1.1', description='Solyc00g277510.1.1', dbxrefs=[]),
 'Solyc00g500048.1.1': SeqRecord(seq=Seq('MEEIHRYLQPDSSQQHNFLYPLIFQEYIYALAQDHGLNRNRSILLENSGYNNKF...SQ*'), id='Solyc00g500048.1.1', name='Solyc00g500048.1.1', description='Solyc00g500048.1.1', dbxrefs=[]),
 'Solyc00g500049.1.1': SeqRecord(seq=Seq('MLNTFSLIGICLNSTLYSSSFFFGKLPEAYAFLNPIVDIMPVIPLFFFLLAFVW...EE*'), id='Solyc00g500049.1.1', name='Solyc00g500049.1.1', description='Solyc00g500049.1.1', dbxrefs=[]),
 'Solyc00g500050.1.1': SeqRecord(seq=Seq('MVTIRADEISNIIRERIEQYNREVKIVNTGTVLQVGDGIARIHGLDEVMAGELV...QA*'), id='Solyc00g500050.1.1', name='Solyc00g500050.1.1', description='Solyc00g500050.1.1', dbxrefs=[]),
 'Solyc00g500051.1.1': SeqRecord(seq=Seq('MEAGVHFGHGTRKWNPKMAPYISAKRKGIHITNLTRTARFLSEACDLVFDAASR...HH*'), id='Solyc00g500051.1.1', name='Solyc00g500051.1.1', description='Solyc00g500051.1.1', dbxrefs=[]),
 'Solyc00g500052.1.1': SeqRecord(seq=Seq('MIDRYKHQQLRIGSVSPQQISAWATKILPNGEIVGETRKEKLSSQSIQLGCPGP...DS*'), id='Solyc00g500052.1.1', name='Solyc00g500052.1.1', description='Solyc00g500052.1.1', dbxrefs=[]),
 'Solyc00g500053.1.1': SeqRecord(seq=Seq('SVDMVFNPLGVPSRMNVGQIFECSLGLAGSLLDRHYRIAPFDERYEQEASRKLV...EA*'), id='Solyc00g500053.1.1', name='Solyc00g500053.1.1', description='Solyc00g500053.1.1', dbxrefs=[]),
 'Solyc00g500054.1.1': SeqRecord(seq=Seq('MTIAIGKFTKDENDLFDIMDDWLRRDRFVFVGWSGLLLFPCAYFAVGGWFTGTT...LN*'), id='Solyc00g500054.1.1', name='Solyc00g500054.1.1', description='Solyc00g500054.1.1', dbxrefs=[]),
 'Solyc00g500055.1.1': SeqRecord(seq=Seq('MDTNRNSTIMARKSLIQREKKRQKLEQKYHSIRRSSKKEISKVPSLSDKWEIYG...GS*'), id='Solyc00g500055.1.1', name='Solyc00g500055.1.1', description='Solyc00g500055.1.1', dbxrefs=[]),
 'Solyc00g500056.1.1': SeqRecord(seq=Seq('MALRFPRFSQGLAQDPTTRRIWFGIATAHDFESHDDITEERLYQNIFASHFGQL...FG*'), id='Solyc00g500056.1.1', name='Solyc00g500056.1.1', description='Solyc00g500056.1.1', dbxrefs=[]),
 'Solyc00g500057.1.1': SeqRecord(seq=Seq('MIIRSPEPEVKILVDRDPVKTSFEEWARPGHFSRTIAKGPDTTTWIWNLHADAH...VG*'), id='Solyc00g500057.1.1', name='Solyc00g500057.1.1', description='Solyc00g500057.1.1', dbxrefs=[]),
 'Solyc00g500058.1.1': SeqRecord(seq=Seq('MSAQSEGNYAEALQNYYEAMRLEIDPYDRSYILYNIGLIHTSNGEHTKALEYYF...FE*'), id='Solyc00g500058.1.1', name='Solyc00g500058.1.1', description='Solyc00g500058.1.1', dbxrefs=[]),
 'Solyc00g500059.1.1': SeqRecord(seq=Seq('MPRSRINGNFIDKTFSIVADILLRVIPTTSGEKEAFTYYRDDSSIKRKVTPRGS...LF*'), id='Solyc00g500059.1.1', name='Solyc00g500059.1.1', description='Solyc00g500059.1.1', dbxrefs=[]),
 'Solyc00g500060.1.1': SeqRecord(seq=Seq('MSAKNYIYIIEGVLYIYLIHPILLFFIVFIVQVHYFSKLRFI*FSLVLV*VYSV...QT*'), id='Solyc00g500060.1.1', name='Solyc00g500060.1.1', description='Solyc00g500060.1.1', dbxrefs=[]),
 'Solyc00g500061.1.1': SeqRecord(seq=Seq('MQGRLSAWLVKHGLIHRSLGFDYQGIETLQIKPEDWHSIAVIFYVYGYNYLRSQ...AH*'), id='Solyc00g500061.1.1', name='Solyc00g500061.1.1', description='Solyc00g500061.1.1', dbxrefs=[]),
 'Solyc00g500062.1.1': SeqRecord(seq=Seq('MAKGGIGMVLAPEYSDNKKKNGKNKIETVMNSIQFPLLDRTAPNSVISTTLNDL...VN*'), id='Solyc00g500062.1.1', name='Solyc00g500062.1.1', description='Solyc00g500062.1.1', dbxrefs=[]),
 'Solyc00g500063.1.1': SeqRecord(seq=Seq('MSSREGFMSPQTETKASVGFKAGVKEYKLTYYTPEYQTKDTDILAAFRVTPQPG...DK*'), id='Solyc00g500063.1.1', name='Solyc00g500063.1.1', description='Solyc00g500063.1.1', dbxrefs=[]),
 'Solyc00g500064.1.1': SeqRecord(seq=Seq('MRINPTTSGSGVSTLEKKNPGRVVQIIGPVLDVAFPPGKMPNIYNALVVQGRDS...KK*'), id='Solyc00g500064.1.1', name='Solyc00g500064.1.1', description='Solyc00g500064.1.1', dbxrefs=[]),
 'Solyc00g500065.1.1': SeqRecord(seq=Seq('MERWWFNSMLFKKEFERRCGLNKSMGSLGPIENTSEDPNLKVKNIHSCSNVDYL...IV*'), id='Solyc00g500065.1.1', name='Solyc00g500065.1.1', description='Solyc00g500065.1.1', dbxrefs=[]),
 'Solyc00g500066.1.1': SeqRecord(seq=Seq('MTWRSDDIWIELITGSRKISSGYDRFDRKEGIVCIFRWGFPGKNRRIFLRFLIK...VF*'), id='Solyc00g500066.1.1', name='Solyc00g500066.1.1', description='Solyc00g500066.1.1', dbxrefs=[]),
 'Solyc00g500067.1.1': SeqRecord(seq=Seq('MAKKKAFTPLFYLASIVFLPWWISFSVNKWLESWVTNWWNTGQSQIVLNNIQEK...NF*'), id='Solyc00g500067.1.1', name='Solyc00g500067.1.1', description='Solyc00g500067.1.1', dbxrefs=[]),
 'Solyc00g500068.1.1': SeqRecord(seq=Seq('MSGSTGERSFADIITSIRYWVIHSITIPSLFIAGWLFVSTGLAYDVFGSPRPNE...QR*'), id='Solyc00g500068.1.1', name='Solyc00g500068.1.1', description='Solyc00g500068.1.1', dbxrefs=[]),
 'Solyc00g500069.1.1': SeqRecord(seq=Seq('MPTIKQLIRNTRQPIRNVTKSPALRGCPQRRGTCTRVDLIVKDLLLDNSWVEPK...SQ*'), id='Solyc00g500069.1.1', name='Solyc00g500069.1.1', description='Solyc00g500069.1.1', dbxrefs=[]),
 'Solyc00g500070.1.1': SeqRecord(seq=Seq('MLYLSMEDENKDLYLFVNSPGGWVIPGIAIYDTMQFVRPDIHTICLGLAASMGS...DL*'), id='Solyc00g500070.1.1', name='Solyc00g500070.1.1', description='Solyc00g500070.1.1', dbxrefs=[]),
 'Solyc00g500071.1.1': SeqRecord(seq=Seq('MGLPWYRVHTVVLNDPGRLLSVHIMHTALVAGWAGSMALYELAVFDPSDPVLDP...AA*'), id='Solyc00g500071.1.1', name='Solyc00g500071.1.1', description='Solyc00g500071.1.1', dbxrefs=[]),
 'Solyc00g500072.1.1': SeqRecord(seq=Seq('MATQTVENSSRSGPRRTAVGDLLKPLNSEYGKVAPGWGTTPLMGVAMALFAGIS...LI*'), id='Solyc00g500072.1.1', name='Solyc00g500072.1.1', description='Solyc00g500072.1.1', dbxrefs=[]),
 'Solyc00g500073.1.1': SeqRecord(seq=Seq('MTEANFGWLIRSVHRWSASMMVLMMILHVFRVYLTGGFKKPRELTWVTGVVLAV...LF*'), id='Solyc00g500073.1.1', name='Solyc00g500073.1.1', description='Solyc00g500073.1.1', dbxrefs=[]),
 'Solyc00g500074.1.1': SeqRecord(seq=Seq('MVREKVTVSTRTLQWKCVESRTDSKRLYYGRFILSPLMKGQADTIGIAMRRALL...IL*'), id='Solyc00g500074.1.1', name='Solyc00g500074.1.1', description='Solyc00g500074.1.1', dbxrefs=[]),
 'Solyc00g500075.1.1': SeqRecord(seq=Seq('MAKAIPKISSRRNGRISSRKGARRIPKGVIHVQASFNNTIVTVTDVRGRVVSWS...RV*'), id='Solyc00g500075.1.1', name='Solyc00g500075.1.1', description='Solyc00g500075.1.1', dbxrefs=[]),
 'Solyc00g500076.1.1': SeqRecord(seq=Seq('MIQPQTHLNVADNSGARELMCIRIIGASNRRYAHIGDVIVAVIKEAVPNMPLER...IW*'), id='Solyc00g500076.1.1', name='Solyc00g500076.1.1', description='Solyc00g500076.1.1', dbxrefs=[]),
 'Solyc00g500077.1.1': SeqRecord(seq=Seq('MKGISYRGNRISFGKYALQALEPAWITSRQIEAGRRAMTRNARRGGKIWVRIFP...IS*'), id='Solyc00g500077.1.1', name='Solyc00g500077.1.1', description='Solyc00g500077.1.1', dbxrefs=[]),
 'Solyc00g500078.1.1': SeqRecord(seq=Seq('MELRIKLVDLFIGKLRPRARGFNFFTVHKDNPKGLWVFFYQLGLSLHHPHGDGL...WM*'), id='Solyc00g500078.1.1', name='Solyc00g500078.1.1', description='Solyc00g500078.1.1', dbxrefs=[]),
 'Solyc00g500079.1.1': SeqRecord(seq=Seq('MPLGTAIHNIEITLGKGGQLARAAGAVAKLIAKEGKSATLKLPSGEVRLISKNC...SK*'), id='Solyc00g500079.1.1', name='Solyc00g500079.1.1', description='Solyc00g500079.1.1', dbxrefs=[]),
 'Solyc00g500080.1.1': SeqRecord(seq=Seq('MAIHLYKTSTPSTRNGTVDSQVKSNPRNNLIYGQRRCGKGRNARGIITARHRGG...AV*'), id='Solyc00g500080.1.1', name='Solyc00g500080.1.1', description='Solyc00g500080.1.1', dbxrefs=[]),
 'Solyc00g500081.1.1': SeqRecord(seq=Seq('MRGHQFKSWIFELREILREIKNSHHFLDSWTQFNSVGSFIHIFFHQERFLKLFD...FM*'), id='Solyc00g500081.1.1', name='Solyc00g500081.1.1', description='Solyc00g500081.1.1', dbxrefs=[]),
 'Solyc00g500082.1.1': SeqRecord(seq=Seq('MYGWYELPKQEFLNSKQPVQIFTTKKYWILFRIGPERRRKAGMPIGIETTLVRS...NK*'), id='Solyc00g500082.1.1', name='Solyc00g500082.1.1', description='Solyc00g500082.1.1', dbxrefs=[]),
 'Solyc00g500083.1.1': SeqRecord(seq=Seq('MLIPQIPSLLLLREKKFTTRGPSTSTRHCSVRLSPIAENSPLLPPESGPCLSPS...TH*'), id='Solyc00g500083.1.1', name='Solyc00g500083.1.1', description='Solyc00g500083.1.1', dbxrefs=[]),
 'Solyc00g500084.1.1': SeqRecord(seq=Seq('MIFQSFLLGNLVSLCMKIINSVVVVGLYYGFLTTFSIGPSYLFLLRALVMEEGT...KV*'), id='Solyc00g500084.1.1', name='Solyc00g500084.1.1', description='Solyc00g500084.1.1', dbxrefs=[]),
 'Solyc00g500085.1.1': SeqRecord(seq=Seq('FSTLEHILTHISFSIVSIVITIHLITFLVDEIVKLYDSSEKGIIVTFFCITGLL...LNE'), id='Solyc00g500085.1.1', name='Solyc00g500085.1.1', description='Solyc00g500085.1.1', dbxrefs=[]),
 'Solyc00g500086.1.1': SeqRecord(seq=Seq('MIIDTTEIETINSFSKLESLKEVYGIIWMLVPIVTLVLGITIGVLVIVWLEREI...SL*'), id='Solyc00g500086.1.1', name='Solyc00g500086.1.1', description='Solyc00g500086.1.1', dbxrefs=[]),
 'Solyc00g500087.1.1': SeqRecord(seq=Seq('MTAPTTRKDLMIVNMGPQHPSMHGVLRLIVTLDGEDVVDCEPILGYLHRGMEKI...DR*'), id='Solyc00g500087.1.1', name='Solyc00g500087.1.1', description='Solyc00g500087.1.1', dbxrefs=[]),
 'Solyc00g500088.1.1': SeqRecord(seq=Seq('MKWLGLVLVWIRQNHSIRSNKYIRSNKYLVLELRNSMARIFSILLFITCVYYLG...ISN'), id='Solyc00g500088.1.1', name='Solyc00g500088.1.1', description='Solyc00g500088.1.1', dbxrefs=[]),
 'Solyc00g500089.1.1': SeqRecord(seq=Seq('MACHHSPWTANTVERRQKWHAITAFGQKHTIERRRAWDDIHRLWTAHTDRTTSG...TT*'), id='Solyc00g500089.1.1', name='Solyc00g500089.1.1', description='Solyc00g500089.1.1', dbxrefs=[]),
 'Solyc00g500090.1.1': SeqRecord(seq=Seq('MPLLTSFDHVCYPKAVMSCHARRRPTNLDKPKRRIIVSPVSPSERQAADLYGVP...DGS'), id='Solyc00g500090.1.1', name='Solyc00g500090.1.1', description='Solyc00g500090.1.1', dbxrefs=[]),
 'Solyc00g500091.1.1': SeqRecord(seq=Seq('WGSESEGNFRSSGDRRVPVRESEVLRENRSISGESMYQNFEDSIINRSISVTLL...TDG'), id='Solyc00g500091.1.1', name='Solyc00g500091.1.1', description='Solyc00g500091.1.1', dbxrefs=[]),
 'Solyc00g011670.1.1': SeqRecord(seq=Seq('MKGQRFKSLQGNKVRHAIFVYMKLVGTSINLHSKLSLALVMKMNIFFKGMKFNL...VF*'), id='Solyc00g011670.1.1', name='Solyc00g011670.1.1', description='Solyc00g011670.1.1', dbxrefs=[]),
 'Solyc00g011660.1.1': SeqRecord(seq=Seq('MANEFHGSSLRSSSPNNPKFIQIITSLDELRRLMLNPVFLEAPHGKAWEVEVEN...LQ*'), id='Solyc00g011660.1.1', name='Solyc00g011660.1.1', description='Solyc00g011660.1.1', dbxrefs=[]),

In [12]:
candidates.head()

,names,logfoldchanges,pvals_adj,description,n_cell_types,cell_types,selected_as
0,Solyc05g006640.4,1.772674,4.101606e-15,Phospholipid-transporting ATPase (AHRD V3.3 **...,2,"['Epidermal', 'Mesophyll']",['mesophyll']
1,Solyc02g082450.3,2.163782,3.950407e-08,Auxin efflux carrier (AHRD V3.3 *** A0A200PYL2...,2,"['Epidermal', 'Mesophyll']",['mesophyll']
2,Solyc02g092450.3,3.237723,1.787920e-02,Calcium-transporting ATPase (AHRD V3.3 *** A0A...,1,['Mesophyll'],['mesophyll']
3,Solyc05g006020.3,7.455045,4.176399e-02,Nucleobase-ascorbate transporter 8 (AHRD V3.3 ...,1,['Mesophyll'],['mesophyll']
4,Solyc07g063520.3,0.872625,1.246746e-08,Organic solute transporter ostalpha protein (D...,3,"['Guard cell', 'Unknown', 'Vascular']",['gaurd']
5,Solyc11g062020.2,1.791141,9.387556e-05,Zinc transporter ZTP29 (AHRD V3.3 *** A0A2G3B9...,2,"['Epidermal', 'Vascular']",['vascular']
6,Solyc01g006150.3,0.754572,5.551576e-03,Cation efflux protein (AHRD V3.3 *** A0A200PY7...,2,"['Epidermal', 'Vascular']",['epidermal']
7,Solyc10g051120.3,1.621479,1.737716e-02,Mitochondrial pyruvate carrier (AHRD V3.3 *** ...,2,"['Epidermal', 'Vascular']",['vascular']
8,Solyc01g106900.3,1.289751,2.896952e-02,Magnesium transporter MRS2-F (AHRD V3.3 *** A0...,1,['Vascular'],['vascular']
9,Solyc09g082890.2,2.456515,1.838875e-05,Calcium-transporting ATPase (AHRD V3.3 *-* A0A...,2,"['Epidermal', 'Guard cell']",['gaurd']
10,Solyc09g075020.3,0.735705,1.252473e-95,ABC transporter C family member 4 (AHRD V3.3 *...,1,['Epidermal'],['epidermal']
11,Solyc05g009020.4,2.289698,2.125228e-15,Mitochondrial carrier protein (AHRD V3.3 *** A...,1,['Epidermal'],['epidermal']
12,Solyc09g065560.3,2.431890,1.252253e-05,Sulfate transporter (AHRD V3.3 *** Q70BL1_BRAOL),1,['Epidermal'],['epidermal']
13,Solyc01g105450.4,0.864790,4.463786e-05,ABC transporter G family member 11 (AHRD V3.3 ...,1,['Epidermal'],['epidermal']
14,Solyc05g051220.3,2.284894,2.638797e-03,Potassium channel GORK (AHRD V3.3 *** A0A1U8GY...,1,['Epidermal'],['epidermal']

In [ ]:
# Convert SeqRecord objects to plain strings for direct use in downstream string operations
id2seq = {k: str(v.seq) for k, v in fasta_dict.items()}

In [17]:
# ITAG4.0 proteome FASTA IDs carry an extra version suffix not present in the candidate gene IDs, so it is stripped before mapping
id2seq_trimmed = {k.rsplit(".", 1)[0]: v for k, v in id2seq.items()}
candidates["seq"] = candidates["names"].map(id2seq_trimmed)

In [18]:
candidates.head()

,names,logfoldchanges,pvals_adj,description,n_cell_types,cell_types,selected_as,seq
0,Solyc05g006640.4,1.772674,4.101606e-15,Phospholipid-transporting ATPase (AHRD V3.3 **...,2,"['Epidermal', 'Mesophyll']",['mesophyll'],MRNRIASSKNIRLGKVQPQAPGHRTVFCNDRDANSLAKFKGNSVST...
1,Solyc02g082450.3,2.163782,3.950407e-08,Auxin efflux carrier (AHRD V3.3 *** A0A200PYL2...,2,"['Epidermal', 'Mesophyll']",['mesophyll'],MGFMTLLEVASMPILQVLIVSGLGAVMATDYLKLLPADARKYLNRI...
2,Solyc02g092450.3,3.237723,1.787920e-02,Calcium-transporting ATPase (AHRD V3.3 *** A0A...,1,['Mesophyll'],['mesophyll'],MESYLNENFGGVKAKHSEEEMLRRWRSLCGVVKNPKRRFRFTANLS...
3,Solyc05g006020.3,7.455045,4.176399e-02,Nucleobase-ascorbate transporter 8 (AHRD V3.3 ...,1,['Mesophyll'],['mesophyll'],MAGGGAAAPPKQDENIPHPVKDQLPNVSYCITSPPPWPEAILLGFQ...
4,Solyc07g063520.3,0.872625,1.246746e-08,Organic solute transporter ostalpha protein (D...,3,"['Guard cell', 'Unknown', 'Vascular']",['gaurd'],MELDLDRGQVTLIASSICLMLTLHFSIQLVTEHFTSWKKPKEQKAI...
5,Solyc11g062020.2,1.791141,9.387556e-05,Zinc transporter ZTP29 (AHRD V3.3 *** A0A2G3B9...,2,"['Epidermal', 'Vascular']",['vascular'],MDSQVLVALGLSLLGGLSTSLGALFVVISQTPNLKMLGLLQGFAAG...
6,Solyc01g006150.3,0.754572,5.551576e-03,Cation efflux protein (AHRD V3.3 *** A0A200PY7...,2,"['Epidermal', 'Vascular']",['epidermal'],MEGEEIKNEVKTPLLDGWKLSYSGRRNSVTTLRGDFLARLPEKVKS...
7,Solyc10g051120.3,1.621479,1.737716e-02,Mitochondrial pyruvate carrier (AHRD V3.3 *** ...,2,"['Epidermal', 'Vascular']",['vascular'],MMKSVRAYLNSPMGPKTTHFWGPMANWGFVISGMMDTKKTPDAISG...
8,Solyc01g106900.3,1.289751,2.896952e-02,Magnesium transporter MRS2-F (AHRD V3.3 *** A0...,1,['Vascular'],['vascular'],MRGVTPPQKFSVPSPDDDADIIRPNTVIPGGVTVGAAMRKKATGVR...
9,Solyc09g082890.2,2.456515,1.838875e-05,Calcium-transporting ATPase (AHRD V3.3 *-* A0A...,2,"['Epidermal', 'Guard cell']",['gaurd'],MMFQANLHYLCMHITLDLPSEVDFSSKKRWHLAFATIYCSRAFEIK...
10,Solyc09g075020.3,0.735705,1.252473e-95,ABC transporter C family member 4 (AHRD V3.3 *...,1,['Epidermal'],['epidermal'],MNLVWFTMDIGKNMAWLTSLSCSASTLESDSGVVEWLRFIFLSPCP...
11,Solyc05g009020.4,2.289698,2.125228e-15,Mitochondrial carrier protein (AHRD V3.3 *** A...,1,['Epidermal'],['epidermal'],MCPLDVIKTRLQVHGLPQVSQSARQGSVIVTSLQNILRTEGFRGLY...
12,Solyc09g065560.3,2.431890,1.252253e-05,Sulfate transporter (AHRD V3.3 *** Q70BL1_BRAOL),1,['Epidermal'],['epidermal'],MGNAEYDEYSSSMKGEKNRKKHQVEIPAAQPFLKSLKNTVKETLFP...
13,Solyc01g105450.4,0.864790,4.463786e-05,ABC transporter G family member 11 (AHRD V3.3 ...,1,['Epidermal'],['epidermal'],MNMSKNGEVLLTWEDLWVTASSLKDGNKAILKGLTGYAKPGQLLAI...
14,Solyc05g051220.3,2.284894,2.638797e-03,Potassium channel GORK (AHRD V3.3 *** A0A1U8GY...,1,['Epidermal'],['epidermal'],MSMKRELREERNGRDSPKEYKMDDLRDSMKSLRSTSRLAMMENELI...

In [20]:
# Confirm every candidate gene ID was successfully mapped to a sequence before proceeding to BLAST
candidates["seq"].isna().sum()

np.int64(0)

In [21]:
candidates.to_csv("../dataset/processed/final_candidates_with_seq.csv", index=False)

In [33]:
# Trailing "*" marks the stop codon in ITAG protein sequences and must be removed for BLAST input
with open("../dataset/blast/tomato_candidates.fasta", "w") as f:
    for name, seq in zip(candidates["names"], candidates["seq"]):
        seq = seq.rstrip("*")
        f.write(f">{name}\n{seq}\n")